# main.yml for GitHub Actions (CI/CD Pipeline)
name: CI/CD Pipeline

on:
  push:
    branches:
      -main

jobs:
  # CI - Build and Test
  build:
    runs-on: ububtu-latest

    steps:
    -name: Checkout code
     uses: actions/checkout@v2

    -name: Set up Python
     uses: actions/setup-python@v2
     with:
       python-version: '3.x'
    
    - name: Install dependencies
      run:
         python -m pip install --upgrade pip
         pip install -r requirement.txt

    - name: Run Unit Tests
      run: 
        pytest
        python -m unittest discover

    -name: Build Success
     if: success()
     run: echo "Build and tests passed!"

  # CD -Deploy to Render
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to Render
      run:
        curl -X POST -H "Authorization: Bearer <your-render-api-token" \
        https://api.render.com/v1/service/<your-service-id>/deploys

#  Extend GitHub Actions to Deploy to Render

# jobs: 
    deploy:
      runs-on: ubuntu-latest
      needs: build

      steps:
      - name: Deploy to Render
        run:
           curl -X POST -H "Authorization: Bearer <your-render-api-token>" \
           https://api.render.com/v1/services/<your-service-id>/deploys
           



